// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package go_sql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Email     string
}
